// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetoHospital;

#nullable disable

namespace ProjetoHospital.Migrations
{
    [DbContext(typeof(ProjetoHospitalContext))]
    [Migration("20251008172919_AddTabelaManutencoes")]
    partial class AddTabelaManutencoes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ProjetoHospital.Entities.Leito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("IdQuarto")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("Ocupado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<bool>("SoftDelete")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("UltimaModificacao")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("IdQuarto");

                    b.ToTable("Leitos", (string)null);
                });

            modelBuilder.Entity("ProjetoHospital.Entities.Limpeza", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataFimLimpeza")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataInicioLimpeza")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("LeitoId")
                        .HasColumnType("int");

                    b.Property<int>("TipoLimpeza")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("LeitoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Limpezas", (string)null);

                    b.HasDiscriminator<int>("TipoLimpeza");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ProjetoHospital.Entities.Manutencao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContatoExecutante")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ContatoSolicitante")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("DataDeConclusao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataDeSolicitacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("NomeExecutante")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NomeSolicitante")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("SetorId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Turno")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TurnoExecutante")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("SetorId");

                    b.ToTable("Manutencoes", (string)null);
                });

            modelBuilder.Entity("ProjetoHospital.Entities.Quarto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Capacidade")
                        .HasColumnType("int");

                    b.Property<int>("IdSetor")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("SoftDelete")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("IdSetor");

                    b.ToTable("Quartos", (string)null);
                });

            modelBuilder.Entity("ProjetoHospital.Entities.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("ProjetoHospital.Entities.Setor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("SoftDelete")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("Setores");
                });

            modelBuilder.Entity("ProjetoHospital.Entities.Usuario", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("ProjetoHospital.Entities.UsuarioRole", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("ProjetoHospital.Entities.LimpezaConcorrente", b =>
                {
                    b.HasBaseType("ProjetoHospital.Entities.Limpeza");

                    b.Property<bool>("LimparBox")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LimparCama")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LimparLixeira")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LimparMesaCabeceira")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LimparPia")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LimparVasoSanitario")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("RevisarMofo")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("TirarLixo")
                        .HasColumnType("tinyint(1)");

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("ProjetoHospital.Entities.LimpezaTerminal", b =>
                {
                    b.HasBaseType("ProjetoHospital.Entities.Limpeza");

                    b.Property<bool>("LimparArmario")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LimparBox")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LimparCama")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LimparChao")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LimparDispensers")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LimparEscadaCama")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LimparLixeira")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LimparMesaCabeceira")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LimparParedes")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LimparPia")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LimparTeto")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LimparVasoSanitario")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("RecolherRoupaSuja")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("RevisarMofo")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("RevisarPapelToalhaEHigienico")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("TirarLixo")
                        .HasColumnType("tinyint(1)");

                    b.ToTable("Limpezas", t =>
                        {
                            t.Property("LimparBox")
                                .HasColumnName("LimpezaTerminal_LimparBox");

                            t.Property("LimparCama")
                                .HasColumnName("LimpezaTerminal_LimparCama");

                            t.Property("LimparLixeira")
                                .HasColumnName("LimpezaTerminal_LimparLixeira");

                            t.Property("LimparMesaCabeceira")
                                .HasColumnName("LimpezaTerminal_LimparMesaCabeceira");

                            t.Property("LimparPia")
                                .HasColumnName("LimpezaTerminal_LimparPia");

                            t.Property("LimparVasoSanitario")
                                .HasColumnName("LimpezaTerminal_LimparVasoSanitario");

                            t.Property("RevisarMofo")
                                .HasColumnName("LimpezaTerminal_RevisarMofo");

                            t.Property("TirarLixo")
                                .HasColumnName("LimpezaTerminal_TirarLixo");
                        });

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("ProjetoHospital.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ProjetoHospital.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ProjetoHospital.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ProjetoHospital.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjetoHospital.Entities.Leito", b =>
                {
                    b.HasOne("ProjetoHospital.Entities.Quarto", "Quarto")
                        .WithMany("Leitos")
                        .HasForeignKey("IdQuarto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Quarto");
                });

            modelBuilder.Entity("ProjetoHospital.Entities.Limpeza", b =>
                {
                    b.HasOne("ProjetoHospital.Entities.Leito", "Leito")
                        .WithMany()
                        .HasForeignKey("LeitoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjetoHospital.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Leito");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ProjetoHospital.Entities.Manutencao", b =>
                {
                    b.HasOne("ProjetoHospital.Entities.Setor", "Setor")
                        .WithMany("Manutencoes")
                        .HasForeignKey("SetorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Setor");
                });

            modelBuilder.Entity("ProjetoHospital.Entities.Quarto", b =>
                {
                    b.HasOne("ProjetoHospital.Entities.Setor", "Setor")
                        .WithMany()
                        .HasForeignKey("IdSetor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Setor");
                });

            modelBuilder.Entity("ProjetoHospital.Entities.UsuarioRole", b =>
                {
                    b.HasOne("ProjetoHospital.Entities.Role", "Role")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjetoHospital.Entities.Usuario", "Usuario")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ProjetoHospital.Entities.Quarto", b =>
                {
                    b.Navigation("Leitos");
                });

            modelBuilder.Entity("ProjetoHospital.Entities.Role", b =>
                {
                    b.Navigation("UsuarioRoles");
                });

            modelBuilder.Entity("ProjetoHospital.Entities.Setor", b =>
                {
                    b.Navigation("Manutencoes");
                });

            modelBuilder.Entity("ProjetoHospital.Entities.Usuario", b =>
                {
                    b.Navigation("UsuarioRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
